"""create netflix table

Revision ID: f8de40499c4c
Revises: 
Create Date: 2021-04-05 13:54:17.211297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8de40499c4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_netflix_show_id', table_name='netflix')
    op.drop_index('ix_netflix_title', table_name='netflix')
    op.drop_table('netflix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netflix',
    sa.Column('show_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('director', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cast', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_added', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('listed_in', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('show_id', name='netflix_pkey')
    )
    op.create_index('ix_netflix_title', 'netflix', ['title'], unique=False)
    op.create_index('ix_netflix_show_id', 'netflix', ['show_id'], unique=False)
    # ### end Alembic commands ###
